name: Copy and Execute Script on Azure VM

on:
  push:
    branches:
      - main
    paths:
      - scripts/*        # Trigger when script is updated
      - .github/workflows/execute-script.yml
  pull_request:
    paths:
      - scripts/*        # Trigger when script is updated
      - .github/workflows/execute-script.yml

env:
  VM_PUBLIC_IP: 172.191.135.200
  script: scripts/install-gatekeeper.sh

jobs:
  deploy-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Upload script to VM
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ env.VM_PUBLIC_IP }}
        username: minikubeadmin
        key: ${{ secrets.AZURE_PRIVATE_KEY }}
        source: "${{ env.script }}"
        target: "~/"
        

    - name: Execute script on VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.VM_PUBLIC_IP }}
        username: minikubeadmin
        key: ${{ secrets.AZURE_PRIVATE_KEY  }}
        run: |
          set -e
          cd ~
          chmod +x ${{ env.script }}
          ./$(basename "${{ env.script }}") | tee ~/install.log
        #   set -e
        #   chmod +x ~/${{ env.script }}
        #   ./${{ env.script }} | tee ~/install.log
        #  # sudo bash ~/${{ env.script }} | tee ~/install.log
