name: Copy and Execute Script on Azure VM

on:
  push:
    branches:
      - main
    paths:
      - scripts/*  # Trigger when script is updated
      - .github/workflows/execute-script.yml
  pull_request:
    paths:
      - scripts/*
      - .github/workflows/execute-script.yml

env:
  VM_PUBLIC_IP: 172.191.135.200
  SCRIPT_PATH: scripts/monitoring.sh

jobs:
  deploy-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload script to VM
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.VM_PUBLIC_IP }}
          username: minikubeadmin
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          source: "${{ env.SCRIPT_PATH }}"
          target: "~/"

      - name: Execute script on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.VM_PUBLIC_IP }}
          username: minikubeadmin
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            cd ~
            chmod +R +x "scritp/*"
            echo "Executing script: "${{ env.SCRIPT_PATH }}"
            sudo bash "${{ env.SCRIPT_PATH }}" | tee ~/install.log