name: Deploy FastAPI App.

on:
  push:
    branches:
      - main
    paths:
      - k8s/**        # Pipleine trigger if anything under /k8s changes
      - .github/workflows/k8s-deploy.yml
      - security/rbac.yml
  pull_request:
    paths:
      - k8s/**
      - .github/workflows/deploy.yml
      - security/rbac.yml

env:
  DOCKER_IMAGE: nedumdocker/fastapi-app
  K8S_NAMESPACE: default
  VM_PUBLIC_IP: 172.191.135.200

jobs:
  checkout-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push staging image
        run: |
          docker builder prune --all --force
          docker build --no-cache -t ${{ env.DOCKER_IMAGE }}:${{ github.run_number }} -t ${{ env.DOCKER_IMAGE }}:latest .
          
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.run_number }}
          docker push ${{ env.DOCKER_IMAGE }}:latest

  deploy-to-k8s:
    needs: checkout-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List files to copy
        run: |
          ls -al
          ls -la ./k8s || echo "k8s folder missing"
          ls -la ./security || echo "security folder missing"

      - name: Copy k8s manifests to VM
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.VM_PUBLIC_IP }}
          username: minikubeadmin
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          #source: "{k8s/*.yml,security/*.yml}"
          source: "./k8s ./security"
          target: "~/"
    
      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Determine changed files
        id: changed
        run: |
          git fetch origin main --depth=2
          echo "changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_OUTPUT
      
      - name: Deploy to Minikube on Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.VM_PUBLIC_IP }}
          username: minikubeadmin
          key: ${{ secrets.AZURE_PRIVATE_KEY }}
          script: | 
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
      
            if echo "$CHANGED" | grep -q "^k8s/"; then
              echo "Changes detected in k8s/, applying manifests..."
              kubectl apply -f ~/k8s/ -n ${{ env.K8S_NAMESPACE }}
              kubectl rollout status deployment/fastapi-app -n ${{ env.K8S_NAMESPACE }}
            fi

            if echo "$CHANGED" | grep -q "^security/rbac.yml$"; then
              echo "RBAC change detected, applying rbac manifest..."
              kubectl apply -f ~/security/rbac.yml -n ${{ env.K8S_NAMESPACE }}
              kubectl rollout status deployment/fastapi-app -n ${{ env.K8S_NAMESPACE }}
            fi
            